Update and rename backup to backup

diff --git a/scripts/backup b/scripts/backup
--- a/scripts/backup
+++ b/scripts/backup
@@ -1,8 +1,28 @@
-#/bin/bash
-# Backup Script for Computer Programming Lab
+#!/bin/bash
 
-# Backup Script takes the backup of the database used by the lab.
-# Since there is no database being used for Computer Programming Lab, 
-# the script does nothing. 
+DB_NAME1="sandeep4_virtual"
+OUT_FILE_NAME="labbackup"
+VERSION="v1.0.4"
+OUT_FILE="$OUT_FILE_NAME-$VERSION.tar"
 
-echo "There is no database used for the lab."
+# take the dump
+mysqldump $DB_NAME1 > $DB_NAME1.sql
+if [ $? -ne 0 ]; then
+  echo "Error: Something went wrong while taking db dump."
+  echo "Aborting backup."
+  exit 1;
+fi
+
+# tar the $DB_NAME folder
+tar cfvz $OUT_FILE $DB_NAME1.sql
+if [ $? -ne 0 ]; then
+  echo "Error: Something went wrong while tar-ing the dump."
+  echo "Aborting backup."
+  exit 1;
+fi
+
+#clean up data
+rm $DB_NAME1.sql
+echo "Backup successful."
+
+exit 0;
